### ISSUE TITLE
[1.16.3] Crash when using workspace made by Quark Oddities backpack

### ISSUE THREAD

**Issue by hibikutek** [Shadows-of-Fire/FastWorkbench#54]
Forge Version 34.1.25
Crashlog [here](https://pastebin.com/832e4w47)

Steps to reproduce:
Open inventory with Quark Oddities backpack equipped.  Click and drag to fill workbench.

**Comment by Shadows-of-Fire** [comment]
That was fixed by https://github.com/Shadows-of-Fire/FastWorkbench/commit/df8549247b5a3afca20b97fb1ec34d29423b7f23
If that fix is no longer sufficient, quark will need to do something on their end, as if I can't catch their container on opening, they need to either not use PlayerContainer, or override PlayerContainer#onCraftMatrixChanged to bypass the coremod hook that I have in place.

**Comment by hibikutek** [comment]
Ah apologies, I didn't see the already closed issue.

I can confirm that with FastWorkbench 4.4.0, the issue is still happening.  Hopefully quark can fix it on their end.

**Comment by frank89722** [comment]
Confirmed this still happen in 1.16.4 with FastWorkbench 4.4.1 and quark 2.4-276
crash report: https://pastebin.com/nxANeDjC
